[[preface]]
= Preface

Spring Data LDAP makes it easier to build Spring-based applications that use the Lightweight Directory Access Protocol (LDAP).

This document is the reference guide for Spring Data - Document Support. It explains Document module concepts and semantics and the syntax for various data store namespaces.


[[get-started:first-steps:spring]]
== Knowing Spring

Spring Data uses the Spring Framework's {spring-framework-docs}core.html[core]
functionality, including:

* {spring-framework-docs}core.html#beans[IoC] container
* {spring-framework-docs}core.html#validation[validation, type conversion and data binding]
* {spring-framework-docs}core.html#expressions[expression language]
* {spring-framework-docs}core.html#aop[AOP]
* {spring-framework-docs}integration.html#jmx[JMX integration]
* {spring-framework-docs}data-access.html[DAO support]
* {spring-framework-docs}data-access.html#dao-exceptions[DAO Exception Hierarchy]

While it is not important to know the Spring APIs, understanding the concepts behind them is important. At a minimum, the idea
behind IoC should be familiar, no matter what IoC container you choose to use.

The core functionality of the LDAP support can be used directly, with no need to invoke the IoC services
of the Spring container. This is much like `JdbcTemplate`, which can be used 'standalone' without any other services
of the Spring container. To use all the features of Spring Data LDAP, such as the repository support,
you must configure some parts of the library by using Spring.

To learn more about Spring, you can refer to the comprehensive {spring-framework-docs}[documentation]
that explains the Spring Framework in detail. There are a lot of articles, blog entries, and books on Spring.
See the Spring Framework https://spring.io/projects/spring-framework/[home page] for more information.

While it is not important to know the Spring APIs, you do need to understand the concepts behind them. At a minimum, the idea behind IoC should be familiar for whatever IoC container you choose to use.

To learn more about Spring, you can refer to the comprehensive documentation that explains the Spring Framework in detail. You can find a lot of articles, blog entries, and books on Spring. See the Spring framework https://spring.io/projects[home page] for more information.

[[requirements]]
== Requirements

Spring Data LDAP 2.x binaries requires JDK level 8.0 or later, https://spring.io/projects/spring-framework/[Spring Framework] {springVersion} or later, and https://spring.io/projects/spring-ldap[Spring LDAP] {springLdapVersion} or later.

[[get-started:help]]
== Additional Help Resources

Learning a new framework is not always straight forward. In this section, we try to provide what we think is an easy-to-follow guide for starting with the Spring Data LDAP module. However, if you encounter issues or are looking for advice, try one or more of the following resources:

[[get-started:help:community]]
Community Forum::
Spring Data on Stackoverflow https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] is a tag for all of Spring Data (not just Document) users to share information and help each other. Note that registration is needed only for posting.

[[get-started:help:professional]]
Professional Support::
Professional, from-the-source support, with guaranteed response time, is available from https://pivotal.io/[Pivotal Sofware, Inc.], the company behind Spring and Spring Data.

[[get-started:up-to-date]]
=== Following Development

For information on the Spring Data LDAP source code repository, nightly builds, and snapshot artifacts, see the https://spring.io/projects/spring-data-ldap/[Spring Data LDAP homepage]. You can help make Spring Data best serve the needs of the Spring community by interacting with developers through the community on https://stackoverflow.com/questions/tagged/spring-data[Stackoverflow]. To follow developer activity, look for the mailing list information on the Spring Data LDAP homepage. If you encounter a bug or want to suggest an improvement, please create a ticket on the Spring Data issue https://github.com/spring-projects/spring-data-ldap/issues[tracker]. To stay up-to-date with the latest news and announcements in the Spring ecosystem, subscribe to the Spring Community https://spring.io[Portal]. Finally, you can follow the Spring https://spring.io/blog[blog] or the project team on Twitter (https://twitter.com/SpringData[SpringData]).

[[get-started:project-metadata]]
=== Project Metadata

* Version Control: https://github.com/spring-projects/spring-data-ldap
* Bugtracker: https://github.com/spring-projects/spring-data-ldap/issues
* Release repository: https://repo.spring.io/libs-release
* Milestone repository: https://repo.spring.io/libs-milestone
* Snapshot repository: https://repo.spring.io/libs-snapshot
