image:https://spring.io/badges/spring-data-ldap/ga.svg[Spring Data LDAP,link=http://projects.spring.io/spring-data-ldap#quick-start]
image:https://spring.io/badges/spring-data-ldap/snapshot.svg[Spring Data LDAP,link=http://projects.spring.io/spring-data-ldap#quick-start]

image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-ldap%2Fmaster&subject=Moore%20(master)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-ldap/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-ldap%2F2.1.x&subject=Lovelace%20(2.1.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-ldap/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-ldap%2F1.0.x&subject=Ingalls%20(1.0.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-ldap/]

= Spring Data LDAP

The primary goal of the http://projects.spring.io/spring-data[Spring Data] project is to make it easier to build Spring-powered applications that use new data access technologies such as non-relational databases, map-reduce frameworks, and cloud based data services.

The Spring Data LDAP project aims to provide familiar and consistent repository abstractions for https://github.com/spring-projects/spring-ldap[Spring LDAP].

== Getting Help

For a comprehensive treatment of all the Spring Data LDAP features, please refer to:

* the http://docs.spring.io/spring-data/ldap/docs/current/reference/html/[User Guide]
* the http://docs.spring.io/spring-data/ldap/docs/current/api/[JavaDocs] have extensive comments in them as well.
* the home page of http://projects.spring.io/spring-data-ldap[Spring Data LDAP] contains links to articles and other resources.
* for more detailed questions, use http://stackoverflow.com/questions/tagged/spring-data-ldap[Spring Data LDAP on Stackoverflow].

If you are new to Spring as well as to Spring Data, look for information about http://projects.spring.io/[Spring projects].

== Quick Start

=== Maven configuration

Add the Maven dependency:

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-ldap</artifactId>
  <version>${version}.RELEASE</version>
</dependency>
----

If you'd rather like the latest snapshots of the upcoming major version, use our Maven snapshot repository and declare the appropriate dependency version.

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-ldap</artifactId>
  <version>${version}.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>spring-libs-snapshot</id>
  <name>Spring Snapshot Repository</name>
  <url>http://repo.spring.io/libs-snapshot</url>
</repository>
----

=== Spring Data repositories

To simplify the creation of data repositories Spring Data LDAP provides a generic repository programming model. It will automatically create a repository proxy for you that adds implementations of finder methods you specify on an interface.

For example, given a `Person` class with first and last name properties, a `PersonRepository` interface that can query for `Person` by last name and when the first name matches a like expression is shown below:

[source,java]
----
public interface PersonRepository extends CrudRepository<Person, Name> {

  List<Person> findByLastname(String lastname);

  List<Person> findByFirstnameLike(String firstname);
}
----

The queries issued on execution will be derived from the method name. Extending `CrudRepository` causes CRUD methods being pulled into the interface so that you can easily save and find single entities and collections of them.

You can have Spring automatically create a proxy for the interface by using the following JavaConfig:

[source,java]
----
@Configuration
@EnableLdapRepositories
class ApplicationConfig {

}
----

This will find the repository interface and register a proxy object in the container. You can use it as shown below:

[source,java]
----
@Service
public class MyService {

  private final PersonRepository repository;

  @Autowired
  public MyService(PersonRepository repository) {
    this.repository = repository;
  }

  public void doWork() {

     repository.deleteAll();

     Person person = new Person();
     person.setFirstname("Rob");
     person.setLastname("Winch");
     person = repository.save(person);

     List<Person> lastNameResults = repository.findByLastname("Winch");
     List<Person> firstNameResults = repository.findByFirstnameLike("Ro*");
 }
}
----

== Contributing to Spring Data

Here are some ways for you to get involved in the community:

* Get involved with the Spring community on Stackoverflow and help out on the http://stackoverflow.com/questions/tagged/spring-data-ldap[spring-data-ldap] tag by responding to questions and joining the debate.
* Create https://jira.spring.io/browse/DATALDAP[JIRA] tickets for bugs and new features and comment and vote on the ones that you are interested in.
* Github is for social coding: if you want to write code, we encourage contributions through pull requests from http://help.github.com/forking/[forks of this repository]. If you want to contribute code this way, please reference a JIRA ticket as well covering the specific issue you are addressing.
* Watch for upcoming articles on Spring by http://spring.io/blog[subscribing] to spring.io.

Before we accept a non-trivial patch or pull request we will need you to https://cla.pivotal.io/sign/spring[sign the Contributor License Agreement]. Signing the contributor’s agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do. If you forget to do so, you'll be reminded when you submit a pull request. Active contributors might be asked to join the core team, and given the ability to merge pull requests.

= Running CI tasks locally

Since this pipeline is purely Docker-based, it's easy to:

* Debug what went wrong on your local machine.
* Test out a a tweak to your `test.sh` script before sending it out.
* Experiment against a new image before submitting your pull request.

All of these use cases are great reasons to essentially run what the CI server does on your local machine.

IMPORTANT: To do this you must have Docker installed on your machine.

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-ldap-github adoptopenjdk/openjdk8:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-data-ldap-github`.
+
2. `cd spring-data-ldap-github`
+
Next, run your tests from inside the container:
+
3. `./mvnw clean dependency:list test -Dsort` (or whatever profile you need to test out)

Since the container is binding to your source, you can make edits from your IDE and continue to run build jobs.

If you test building the artifact, do this:

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-ldap-github adoptopenjdk/openjdk8:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-data-ldap-github`.
+
2. `cd spring-data-ldap-github`
+
Next, try to package everything up from inside the container:
+
3. `./mvnw -Pci,snapshot -Dmaven.test.skip=true clean package`

NOTE: Docker containers can eat up disk space fast! From time to time, run `docker system prune` to clean out old images.

